# site settings
title: Dynamics Retail Notebook
description: "Learn about GitHub pages and Jekyll."
keywords: "github, github-pages, websites, static gen, hosting, html, workshop, gh-pages"

# author settings for cc-by
author: Amit Kumar
pub_year: 2018

# Build settings
markdown: kramdown
