# site settings
title: Dynamics Retail Notebook
description: "Learn Microsoft Dynamics AX/365 retail in depth. Get help on architecture/implementation of Microsoft Dynamics for Retail. Get your problem solved and learn trending things in Retail."
keywords: "Retail, Dynamics Retail, Dynamics 365 for Retail, Microsoft Retail, Microsoft MPOS, Dynamics MPOS, MPOS, CPOS, Dynamics Retail Server"
url: https://dynamicsretailnotes.com
enforce_ssl: dynamicsretailnotes.com

# author settings
author: Amit Kumar
pub_year: 2018

# webmaster settings
google_webmaster: hYCXt37cDN7Fw-GJ1sHiXuqM198SY8JBk83vt1f1zGo
bing_webmaster: 7B2D64A1E9E1E53A1E70AA094DA129AA

# analytics settings
google_analytics: 'UA-132742277-1'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/
destination: ./_site

sass:
    style: compressed

# plugin settings
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
