# site settings
title: Dynamics Retail Notebook
description: "Learn Microsoft Dynamics AX/365 retail in depth. Get help on architecture/implementation of Microsoft Dynamics for Retail. Get your problem solved and learn trending things in Retail."
keywords: "Retail, Dynamics Retail, Dynamics 365 for Retail, Microsoft Retail, Microsoft MPOS, Dynamics MPOS, MPOS, CPOS, Dynamics Retail Server"
email: "amitkumar17@outlook.com"

# author settings
author: Amit Kumar
pub_year: 2018

# Build settings
markdown: kramdown

# Permalink settings
permalink: :title

# sitemap settings
plugins:
  - jekyll-sitemap
  - jekyll-feed
