# site settings
title: Dynamics Retail Notebook
description: "Learn Microsoft Dynamics AX/365 for Retail in depth. Get help on architecture/implementation of Microsoft Dynamics for Retail. Get your problem solved and learn trending things in Retail."
keywords: "Retail, Dynamics Retail, Dynamics 365 for Retail, Microsoft Retail, Microsoft MPOS, Dynamics MPOS, MPOS, CPOS, Dynamics Retail Server"
baseurl: https://dynamicsretailnotes.com
url: https://dynamicsretailnotes.com
enforce_ssl: dynamicsretailnotes.com

# author settings
author: Amit Kumar
pub_year: 2019

# webmaster settings
webmaster_verifications:
  google: hYCXt37cDN7Fw-GJ1sHiXuqM198SY8JBk83vt1f1zGo
  bing: 7B2D64A1E9E1E53A1E70AA094DA129AA

# build settings
include: ['_pages']
markdown: kramdown
permalink: :title

# SASS settings
sass:
    style: compressed

# sitemap settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
